/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/hexagon.glb -o src/components/Hexagon.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import React, { useRef } from "react";

export function Hexagon({ color, ...props }) {
  const rb = useRef();
  const { nodes, materials } = useGLTF("/models/hexagon.glb", "draco/gltf/");

  return (
    <RigidBody {...props} type={"fixed"} name="hexagon" colliders="hull" >
      <mesh geometry={nodes.Hexagon.geometry} material={materials.hexagon}>
        <meshStandardMaterial
          {...materials.hexagon}
          color={color}
          transparent
        />
      </mesh>
    </RigidBody>
  );
}

useGLTF.preload("/models/hexagon.glb", "draco/gltf/");
